### ISSUE TITLE
POST requests should return a 201 status

### ISSUE THREAD

**Issue by machinshin** [sebelga/gstore-api#2]
So I noted that you're using the default `res.json` everywhere, which is fine for the most part, but.. technically, according to HTTP the status code for an object creation is `201 CREATED`

**Comment by loixlab** [comment]
You're right 👍  I am going to change that. Any other status code I might have been missing?

**Comment by machinshin** [comment]
an example on how to add additional routes would be cool. i believe I can  get access to the router by doing this, right?

`const rtr = apiBuilder.create(....).router;
rtr.get('/:id', (req, res) => { .. });`
, but that's not entirely clear. 

as far as the HTTP codes, `DELETE` is generally expected to return `204 No-Content` (though I could possibly make an argument for ` 410 Gone`)

**Comment by loixlab** [comment]
You can add all the routes like always with the Express router.
I like to separate my routes by modules but here a short example with all the routes in 1 file

```js
// routes.js
const router = require('express').Router();
const gstoreApi = require('gstore-api')();
const apiBuilder = gstoreApi.express(router);

// api for blog-posts
const BlogPost = require('./blog-post.model');
const blogPostApi = apiBuilder.create(BlogPost);

// api for users
const User = require('./user.model');
const userApi = apiBuilder.create(User);

// create any other routes..
router.get('/something', someController.someMethod);
router.get('/something/else', someController.someMethod2);
router.get('/something/else/:id', someController.someMethod3);
...

module.exports = (app) {
    // api
    app.use('/api/v1', blogPostApi );
    app.use('/api/v1', userApi);

    // other
    app.use(router);
}
```

Your main app file
```js
// index.js

const express = require('express');
const app = express();

require('./routes')(app);

...
```

**Comment by loixlab** [comment]
Thanks for the PR. I just published a new release with you changes. 👍
