### ISSUE TITLE
errorsHandler does not set proper HTTP code

### ISSUE THREAD

**Issue by shauravg** [sebelga/gstore-api#4]
This may be a rare case. I am not sure since I didn't look into too much, but the problem occurred when my  keyFilename property in datastore() was not pointing to a valid file. It rightly throws an error on model.save and then goes into errorsHandler which attempts to set the return HTTP code to MODULE_NOT_FOUND which is the error of google datastore and not a valid HTTP error afaik. This error is converted to 0 which is not acceptable to express and it throws an unhandled promise rejection and the client waits forever for server to return something. 

For a temp fix, I went ahead and changed Line 10 to:
error_code:err.code,

**Comment by loixlab** [comment]
Hi,
Thanks for reporting, I am now out on holidays. I will have a look into this next week and apply a patch.  

Do you mean here: "my keyFilename property in datastore() was not pointing to a valid file." an **IN**valid file ?

thanks

**Comment by shauravg** [comment]
Awesome, thanks! Other than that, this was a great library to use. 

Yes, good catch. I meant "invalid".

**Comment by loixlab** [comment]
Hi, I just released a patch version to fix the problem. It was quiet strange as if you pass a wrong "keyFilename" the issue was there. But if you use the "GOOGLE_APPLICATION_CREDENTIALS" environment variable it didn't occur.
thanks for reporting!
